version: '3.3'

services:
 php:
  build:
   context: .
   dockerfile: dockerfile
  container_name: php81
  depends_on:
   - db
  image: php:8.1-apache
  volumes:
   - ./src:/var/www/html/
  ports:
   - 7000:80
 db:
  container_name: mysql8
  image: mysql:8.0
  command: --default-authentication-plugin=mysql_native_password
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: tp-api
   MYSQL_USER: myself
   MYSQL_PASSWORD: myself
  ports:
   - 3366:3306

 phpmya:
  image: phpmyadmin/phpmyadmin:latest
  container_name: phpmyadmin
  environment:
    PMA_ARBITRARY: 1
    PMA_HOST: db
    PMA_USER: myself
    PMA_PASSWORD: myself
    UPLOAD_LIMIT: 20M
  ports:
  - 8899:80